name: Main Workflow

on:
    push:
        branches:
            - develop2
            - release/*
            - *
    pull_request:
        branches:
            - '*'
            - 'release/*'
    workflow_dispatch:


jobs:
    linux-tests:
        uses: ./.github/workflows/linux-tests.yml
    osx-tests:
        uses: ./.github/workflows/osx-tests.yml
    windows-tests:
        uses: ./.github/workflows/windows-tests.yml


    final-job:
        runs-on: ubuntu-latest
        needs: [ linux-tests, osx-tests, windows-tests ]
        steps:
            -   run: echo "All jobs are done. Executing the final job."
