name: Main Workflow
on:
  push:
    branches:
      - develop2
      - release/*
      - '*'
  pull_request:
    branches:
      - '*'
      - 'release/*'
  workflow_dispatch:

jobs:
  linux-tests:
    uses: ./.github/workflows/linux-tests.yml
  osx-tests:
    uses: ./.github/workflows/osx-tests.yml
  windows-tests:
    uses: ./.github/workflows/win-tests.yml
  code_coverage:
    runs-on: ubuntu-latest
    needs: [linux-tests, osx-tests, windows-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Merge coverage reports
        run: |
          pip install coverage
          coverage combine
          coverage report
          coverage xml -o merged-coverage.xml
          coverage html -d coverage-html
